### ISSUE TITLE
Build Failed due to leftShift() method not found in ":scalarinputapi:generateRelease" 

### ISSUE THREAD

**Issue by rlogical-techsoft** [google/science-journal#38]
I am getting issue while importing project in Android Studio.

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method leftShift() for arguments [android_release_aar_8aaffqenud6qsg8w8hrovmfvc$
_run_closure7@5f35a04c] on task ':scalarinputapi:generateRelease' of type org.gradle.api.DefaultTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:179)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:164)
        at org.gradle.api.DefaultTask_Decorated.invokeMethod(Unknown Source)
        at android_release_aar_8aaffqenud6qsg8w8hrovmfvc.run(https://raw.githubusercontent.com/ArthurHub/release-android-library/master/android-release-aar.gradle:62)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
```
I can see there is `<<` available in "https://raw.githubusercontent.com/ArthurHub/release-android-library/master/android-release-aar.gradle" and this is deprecated android not allowed this.

I have research on this issue but not getting the solution. 

Please help me..

Thank you

**Comment by JeneaVranceanu** [comment]
Hi, @rlogical-techsoft ! I resolved the issue by downloading Gradle file behind this link. File was added to the same level as the build.gradle that uses this file. 

`<<` was replaced with `doLast { ... }`. The solution is not good because file behind this link may change but you won't receive any updates.

The other solution would be to lower Gradle version to 4.*. In version 4.* sign `<<` was deprecated but still used. In 5.* it was removed.

**Comment by lizlooney** [comment]
Thanks for the bug report. I'll take a look.

**Comment by rlogical-techsoft** [comment]
@lizlooney : You mean you have downloaded the android-release-aar.gradle file and replaced << with doLast { ... }. Where you have placed in code or uploaded?

**Comment by JeneaVranceanu** [comment]
@rlogical-techsoft 
Downloaded and physically placed the file on the same level as build.gradle that uses this file.

<img width="264" alt="Screenshot 2019-07-01 at 09 21 15" src="https://user-images.githubusercontent.com/36865532/60414755-ca91a400-9be1-11e9-8daf-afde2184be97.png">

In build gradle next line

`apply from: 'https://raw.githubusercontent.com/ArthurHub/release-android-library/master/android-release-aar.gradle'`

was changed to 

`apply from: 'android-release-aar.gradle'`
