### ISSUE TITLE
Start observing called earlier than scanSensors?

### ISSUE THREAD

**Issue by berndporr** [google/science-journal#8]
Seems so that start observers is called at the very start when ScienceJournal starts and then only later the scan Sensors.
The way I do it that ScanSensors first checks if the bluetooth dev is paired, then populates behaviour etc. 
The in startObserving I use the bluetooth dev which I've found in ScanSensors. That fails because scanSensors hasn't been called.
When I press "retry" then that works because then the ScanSensors has been executed.
I can avoid this by moving the bluetooth detection also in the observer and do it at least once but that feels not right. What's the best approach of doing it? I'm pretty sure that before the update last week that order was the other way around.

From line 210:
https://github.com/glasgowneuro/AttysPlot/blob/master/app/src/main/java/tech/glasgowneuro/www/attysplot/Attys2ScienceJournal.java

```
Log (starting program, then fails, then I press retry and then it works):
`10-18 00:42:10.008 565-841/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Start observing on sensorID:7
10-18 00:42:10.008 565-841/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Finding paired attys
10-18 00:42:10.010 565-613/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Start observing on sensorID:6
10-18 00:42:10.010 565-613/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Finding paired attys
10-18 00:42:10.012 565-841/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Found an Attys as a paired device
10-18 00:42:10.013 565-613/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Found an Attys as a paired device
10-18 00:42:10.015 565-4265/tech.glasgowneuro.www.attysplot V/AttysComm: Got rfComm socket!
10-18 00:42:10.114 565-4264/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.115 565-4265/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.387 565-4264/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.455 565-4265/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Retrying to connect
10-18 00:42:10.555 565-4265/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.828 565-4264/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.830 565-4264/tech.glasgowneuro.www.attysplot D/AttysComm: Could not establish connection to Attys: read failed, socket might closed or timeout, read ret: -1
10-18 00:42:10.833 565-4264/tech.glasgowneuro.www.attysplot E/AttysComm: Could not get streams
                                                                         java.io.IOException: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.connectToAttys(AttysComm.java:577)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.run(AttysComm.java:803)
                                                                          Caused by: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                             at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:684)
                                                                             at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:643)
                                                                             at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:377)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.connectToAttys(AttysComm.java:559)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.run(AttysComm.java:803) 
10-18 00:42:10.889 565-4265/tech.glasgowneuro.www.attysplot D/AttysComm: Last resort: we try the hidden API
10-18 00:42:10.990 565-4265/tech.glasgowneuro.www.attysplot W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
10-18 00:42:10.993 565-4265/tech.glasgowneuro.www.attysplot D/AttysComm: Could not establish connection to Attys: read failed, socket might closed or timeout, read ret: -1
10-18 00:42:10.993 565-4265/tech.glasgowneuro.www.attysplot E/AttysComm: Could not get streams
                                                                         java.io.IOException: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.connectToAttys(AttysComm.java:577)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.run(AttysComm.java:803)
                                                                          Caused by: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                             at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:684)
                                                                             at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:643)
                                                                             at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:377)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.connectToAttys(AttysComm.java:559)
                                                                             at tech.glasgowneuro.www.attysplot.AttysComm.run(AttysComm.java:803) 
10-18 00:42:17.564 565-612/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Keep connection alive.
10-18 00:42:17.584 565-841/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Start observing on sensorID:6
10-18 00:42:19.569 565-613/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: shutting down sensor 7.
10-18 00:42:19.569 565-613/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Keep connection alive.
10-18 00:42:19.590 565-661/tech.glasgowneuro.www.attysplot D/Attys2ScienceJournal: Start observing on sensorID:7
`
```

**Comment by scrubskip** [comment]
You shouldn't rely on the scan to be happening before start observing. If you have the Bluetooth address, then call BluetoothAdapter#getRemoteDevice(String) to get the BluetoothDevice, then you can set up your behavior from there.

**Comment by berndporr** [comment]
You mean everything relating to establishing an active bluetooth connection should happen basically within startObserving? That's the way I've coded it just now. Start observing is called per sensor whereas scanSensors is essentially called per (bluetooth-)device (?). Would make more sense to get the bluetooth device there and then use it in startObserving?
If the scan where only run after calling the settings menu then I'd understand that everything had to be in startObserving but since it's also called every time I start scienceJournal it could host the call to get the bluetooth device?
Either way happy to have everything in startObserving. Just trying to understand what the idea is behind it to get it right.

**Comment by berndporr** [comment]
It's not a big deal. I've sorted it. Just made the bluetoothDevice a local variable in both methods so they can work independently. thanks for your reply!
